# Day 3 Assignment

# Question 1

In [2]:
import numpy as np

In [4]:
arr=np.arange(2,50,3)

print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [14]:
list1=[2,5,6,4,7]
list2=[5,6,9,8,1]
list=[*list1,*list2]
print(list)
list1=np.array(list1)
list2=np.array(list2)
list.sort()
print(list)



[2, 5, 6, 4, 7, 5, 6, 9, 8, 1]
[1, 2, 4, 5, 5, 6, 6, 7, 8, 9]


# Question 3

In [15]:
arr=np.array([1,2,3,4,5,6])
print(type(arr))
print(arr.ndim)
print(arr.size)

<class 'numpy.ndarray'>
1
6


# Question 4

In [16]:
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(b)
b=b.reshape(4,3)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Question 5

In [17]:
s1=np.arange(16).reshape(4,4)
s2=np.arange(16).reshape(4,4)
print("Stacking vertically")
print(np.hstack((s1,s2)))
print("------------------------")
print("Stacking horizontally")
print(np.vstack((s1,s2)))

Stacking vertically
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]
 [12 13 14 15 12 13 14 15]]
------------------------
Stacking horizontally
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


# Question 6

In [18]:
number_list = np.array([1, 1, 2, 3, 4, 4, 1])
(unique, counts) = np.unique(number_list, return_counts=True)
frequencies = np.asarray((unique, counts)).T
print(frequencies)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
